#autohotkey script will be watching for the postProcessNow file to appear.  When it does, Autohotkey will send to Solidworks the keystroke that I set in Solidworks to run the HSMWorks "Post Process" function.
default:
	touch postProcessNow 
	